# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT sports.wsgi

beta_settings:
    cloud_sql_instances: pronosticodelaraza:us-central1:pdlr

runtime_config:
  python_version: 3
# [END runtime]
