# Generated by Django 2.0.2 on 2018-02-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_date', models.DateTimeField(verbose_name='Fecha')),
                ('resultado', models.CharField(choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita')], max_length=1)),
                ('puntosLocal_int', models.IntegerField(default=0)),
                ('puntosVisita', models.IntegerField(default=0)),
                ('empezo_bool', models.BooleanField(default=False)),
                ('termino_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_text', models.CharField(max_length=200)),
                ('escudo_text', models.CharField(max_length=200)),
                ('camiseta_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_text', models.CharField(max_length=200)),
                ('inicio_date', models.DateTimeField(verbose_name='Arranque')),
                ('fin_date', models.DateTimeField(verbose_name='Final')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga_text', models.CharField(max_length=200)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_text', models.CharField(max_length=200)),
                ('inicio_date', models.DateTimeField(verbose_name='Arranque')),
                ('fin_date', models.DateTimeField(verbose_name='Final')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Liga')),
            ],
        ),
        migrations.AddField(
            model_name='jornada',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Temporada'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Liga'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jornada'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='main.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='main.Equipo'),
        ),
    ]
