# Generated by Django 2.0.2 on 2018-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='scoreLocal_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='scoreVisita',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='fecha_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='resultado',
            field=models.CharField(choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita')], max_length=1, null=True),
        ),
    ]
