# Generated by Django 2.0.2 on 2018-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180228_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuentro',
            old_name='scoreVisita',
            new_name='scoreVisita_int',
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='resultado',
            field=models.CharField(choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita'), ('NA', 'Sin resultado')], max_length=1, null=True),
        ),
    ]
