# Generated by Django 2.0.2 on 2018-02-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180228_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='main.Equipo'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='puntosLocal_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='puntosVisita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='resultado',
            field=models.CharField(blank=True, choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita'), ('NA', 'Sin resultado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='scoreLocal_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='scoreVisita_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='main.Equipo'),
        ),
    ]
