# Generated by Django 2.0.2 on 2018-03-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180228_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='resultado',
            field=models.CharField(blank=True, choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita'), ('N', 'Sin Resultado')], max_length=1, null=True),
        ),
    ]
