# Generated by Django 2.0.2 on 2018-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180302_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo_bool',
            field=models.BooleanField(default=True),
        ),
    ]
