# Generated by Django 2.0.2 on 2018-03-02 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_equipo_activo_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolAmigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_text', models.CharField(max_length=200)),
                ('imagen_text', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_date', models.DateTimeField(verbose_name='creado')),
                ('publico_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiniela_text', models.CharField(max_length=200)),
                ('imagen_text', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_date', models.DateTimeField(verbose_name='creado')),
                ('public_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='relQuinEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Encuentro')),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quiniela')),
            ],
        ),
        migrations.CreateModel(
            name='relQuinPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PoolAmigos')),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quiniela')),
            ],
        ),
        migrations.CreateModel(
            name='relUserPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_date', models.DateTimeField(verbose_name='creado')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PoolAmigos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
