# Generated by Django 2.0.2 on 2018-03-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_poolamigos_quiniela_relquinenc_relquinpool_reluserpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='descripcion_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
