# Generated by Django 2.0.2 on 2018-03-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_quiniela_descripcion_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_marcador', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visita'), ('N', 'Sin Resultado')], max_length=1, null=True)),
                ('scoreLocal_int', models.IntegerField(blank=True, null=True)),
                ('scoreVisita_int', models.IntegerField(blank=True, null=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Encuentro')),
            ],
        ),
    ]
