# Generated by Django 2.0.2 on 2018-03-03 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_pronostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pronostico',
            unique_together={('usuario', 'encuentro')},
        ),
        migrations.AlterUniqueTogether(
            name='relquinenc',
            unique_together={('quiniela', 'encuentro')},
        ),
        migrations.AlterUniqueTogether(
            name='relquinpool',
            unique_together={('quiniela', 'pool')},
        ),
        migrations.AlterUniqueTogether(
            name='reluserpool',
            unique_together={('usuario', 'pool')},
        ),
    ]
