# Generated by Django 2.0.2 on 2018-03-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pronostico_candado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateTimeField(verbose_name='Inicial')),
                ('fecha_final', models.DateTimeField(verbose_name='Final')),
            ],
        ),
    ]
