# Generated by Django 2.0.2 on 2018-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('league', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('home', models.CharField(max_length=200)),
                ('away', models.CharField(max_length=200)),
                ('hg', models.IntegerField(blank=True, null=True)),
                ('ag', models.IntegerField(blank=True, null=True)),
                ('res', models.CharField(max_length=1)),
                ('ph', models.FloatField()),
                ('pd', models.FloatField()),
                ('pa', models.FloatField()),
                ('maxh', models.FloatField()),
                ('maxd', models.FloatField()),
                ('maxa', models.FloatField()),
                ('avgh', models.FloatField()),
                ('avgd', models.FloatField()),
                ('avga', models.FloatField()),
            ],
        ),
    ]
