# Generated by Django 2.0.2 on 2018-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='filtros',
            name='importar_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
