# Generated by Django 2.0.2 on 2018-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180310_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='avga',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='avgd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='avgh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='maxa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='maxd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='maxh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='pa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='res',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
