# Generated by Django 2.0.2 on 2018-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180311_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='pctEmpte_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pronostico',
            name='pctLocal_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pronostico',
            name='pctVisita_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
